# Generated by Django 4.2.6 on 2024-05-22 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('idNoticia', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('data_publi', models.CharField(max_length=20)),
                ('referencias', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
