# Generated by Django 4.2.6 on 2024-05-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0002_forum_delete_noticia'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Forum',
            new_name='Noticia',
        ),
    ]
