# Generated by Django 5.0.2 on 2024-07-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complexidade', models.CharField(max_length=7)),
                ('titulo', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=7)),
            ],
        ),
    ]
