# Generated by Django 5.0.2 on 2024-07-22 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biblioteca',
            name='arquivo',
            field=models.CharField(default='https://example.com', max_length=100),
        ),
    ]
