# Generated by Django 5.0.2 on 2024-07-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_biblioteca_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biblioteca',
            name='arquivo',
            field=models.URLField(default='https://example.com', max_length=100),
        ),
    ]
