# Generated by Django 4.2.6 on 2024-07-20 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticias_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticias',
            name='data_publi',
            field=models.DateTimeField(max_length=8),
        ),
    ]
