# Generated by Django 4.2.6 on 2024-05-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('criador', models.CharField(max_length=100)),
                ('data_criação', models.CharField(max_length=20)),
                ('CPF', models.CharField(default='-', max_length=11, primary_key=True, serialize=False, unique=True)),
                ('categoria', models.CharField(max_length=200)),
            ],
        ),
    ]
