# Generated by Django 4.2.6 on 2024-05-22 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_rename_usuario_forum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forum',
            name='CPF',
        ),
        migrations.AddField(
            model_name='forum',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
