# Generated by Django 5.0.2 on 2024-07-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profissionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=150)),
                ('cr', models.IntegerField()),
                ('telefone', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=200)),
            ],
        ),
    ]
