# Generated by Django 5.0.2 on 2024-07-09 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_profissionais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profissionais',
            name='cr',
            field=models.CharField(max_length=20),
        ),
    ]
